/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockPriceOracleSol from "./MockPriceOracle.sol";
export type { mockPriceOracleSol };
import type * as uniswapV2PriceOracleSol from "./UniswapV2PriceOracle.sol";
export type { uniswapV2PriceOracleSol };
import type * as stakingSol from "./staking.sol";
export type { stakingSol };
import type * as tokenSol from "./token.sol";
export type { tokenSol };
export type { SimpleToken } from "./SimpleToken";
