/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockPriceOracleSol from "./MockPriceOracle.sol";
export type { mockPriceOracleSol };
import type * as uniswapV3PriceOracleSol from "./UniswapV3PriceOracle.sol";
export type { uniswapV3PriceOracleSol };
import type * as stakingSol from "./staking.sol";
export type { stakingSol };
export type { SimpleToken } from "./SimpleToken";
