/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ABDSStaking {
  export type StakeStruct = {
    amount: BigNumberish;
    startTime: BigNumberish;
    duration: BigNumberish;
    apr: BigNumberish;
    earlyClaimAllowed: boolean;
  };

  export type StakeStructOutput = [
    amount: bigint,
    startTime: bigint,
    duration: bigint,
    apr: bigint,
    earlyClaimAllowed: boolean
  ] & {
    amount: bigint;
    startTime: bigint;
    duration: bigint;
    apr: bigint;
    earlyClaimAllowed: boolean;
  };
}

export interface ABDSStakingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADDITIONAL_REWARD_APR"
      | "Claim"
      | "abdsToken"
      | "boost"
      | "currentReward"
      | "getUserStake"
      | "getUserStakes"
      | "lastRewardTime"
      | "owner"
      | "renounceOwnership"
      | "setExtraAPR"
      | "stakeTokens"
      | "transferOwnership"
      | "uniswapOracle"
      | "usdcToken"
      | "usdtToken"
      | "userStakes"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RewardsWithdrawn"
      | "StakeDurationExtended"
      | "Staked"
      | "UnlockedStakesWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADDITIONAL_REWARD_APR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "Claim", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "abdsToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "boost",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStake",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStakes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastRewardTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setExtraAPR",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeTokens",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapOracle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdtToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userStakes",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "ADDITIONAL_REWARD_APR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "Claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "abdsToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "boost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRewardTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExtraAPR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdtToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userStakes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsWithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    reward: BigNumberish,
    tokenType: BigNumberish
  ];
  export type OutputTuple = [user: string, reward: bigint, tokenType: bigint];
  export interface OutputObject {
    user: string;
    reward: bigint;
    tokenType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeDurationExtendedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    duration: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, duration: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    duration: BigNumberish,
    apr: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    duration: bigint,
    apr: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    duration: bigint;
    apr: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnlockedStakesWithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    stakeAmount: BigNumberish,
    rewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    stakeAmount: bigint,
    rewardAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    stakeAmount: bigint;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ABDSStaking extends BaseContract {
  connect(runner?: ContractRunner | null): ABDSStaking;
  waitForDeployment(): Promise<this>;

  interface: ABDSStakingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADDITIONAL_REWARD_APR: TypedContractMethod<[], [bigint], "view">;

  Claim: TypedContractMethod<[tokenType: BigNumberish], [void], "nonpayable">;

  abdsToken: TypedContractMethod<[], [string], "view">;

  boost: TypedContractMethod<
    [index: BigNumberish, additionaldays: BigNumberish],
    [void],
    "nonpayable"
  >;

  currentReward: TypedContractMethod<[], [bigint], "view">;

  getUserStake: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [ABDSStaking.StakeStructOutput],
    "view"
  >;

  getUserStakes: TypedContractMethod<
    [user: AddressLike],
    [ABDSStaking.StakeStructOutput[]],
    "view"
  >;

  lastRewardTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setExtraAPR: TypedContractMethod<
    [_extraAPR: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakeTokens: TypedContractMethod<
    [
      _amount: BigNumberish,
      _duration: BigNumberish,
      _earlyClaimAllowed: boolean
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uniswapOracle: TypedContractMethod<[], [string], "view">;

  usdcToken: TypedContractMethod<[], [string], "view">;

  usdtToken: TypedContractMethod<[], [string], "view">;

  userStakes: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        amount: bigint;
        startTime: bigint;
        duration: bigint;
        apr: bigint;
        earlyClaimAllowed: boolean;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADDITIONAL_REWARD_APR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "Claim"
  ): TypedContractMethod<[tokenType: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "abdsToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "boost"
  ): TypedContractMethod<
    [index: BigNumberish, additionaldays: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserStake"
  ): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [ABDSStaking.StakeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserStakes"
  ): TypedContractMethod<
    [user: AddressLike],
    [ABDSStaking.StakeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastRewardTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExtraAPR"
  ): TypedContractMethod<[_extraAPR: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeTokens"
  ): TypedContractMethod<
    [
      _amount: BigNumberish,
      _duration: BigNumberish,
      _earlyClaimAllowed: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uniswapOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdtToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userStakes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        amount: bigint;
        startTime: bigint;
        duration: bigint;
        apr: bigint;
        earlyClaimAllowed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardsWithdrawn"
  ): TypedContractEvent<
    RewardsWithdrawnEvent.InputTuple,
    RewardsWithdrawnEvent.OutputTuple,
    RewardsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "StakeDurationExtended"
  ): TypedContractEvent<
    StakeDurationExtendedEvent.InputTuple,
    StakeDurationExtendedEvent.OutputTuple,
    StakeDurationExtendedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "UnlockedStakesWithdrawn"
  ): TypedContractEvent<
    UnlockedStakesWithdrawnEvent.InputTuple,
    UnlockedStakesWithdrawnEvent.OutputTuple,
    UnlockedStakesWithdrawnEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardsWithdrawn(address,uint256,uint8)": TypedContractEvent<
      RewardsWithdrawnEvent.InputTuple,
      RewardsWithdrawnEvent.OutputTuple,
      RewardsWithdrawnEvent.OutputObject
    >;
    RewardsWithdrawn: TypedContractEvent<
      RewardsWithdrawnEvent.InputTuple,
      RewardsWithdrawnEvent.OutputTuple,
      RewardsWithdrawnEvent.OutputObject
    >;

    "StakeDurationExtended(address,uint256,uint256)": TypedContractEvent<
      StakeDurationExtendedEvent.InputTuple,
      StakeDurationExtendedEvent.OutputTuple,
      StakeDurationExtendedEvent.OutputObject
    >;
    StakeDurationExtended: TypedContractEvent<
      StakeDurationExtendedEvent.InputTuple,
      StakeDurationExtendedEvent.OutputTuple,
      StakeDurationExtendedEvent.OutputObject
    >;

    "Staked(address,uint256,uint256,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "UnlockedStakesWithdrawn(address,uint256,uint256)": TypedContractEvent<
      UnlockedStakesWithdrawnEvent.InputTuple,
      UnlockedStakesWithdrawnEvent.OutputTuple,
      UnlockedStakesWithdrawnEvent.OutputObject
    >;
    UnlockedStakesWithdrawn: TypedContractEvent<
      UnlockedStakesWithdrawnEvent.InputTuple,
      UnlockedStakesWithdrawnEvent.OutputTuple,
      UnlockedStakesWithdrawnEvent.OutputObject
    >;
  };
}
