/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPriceOracle__factory } from "./IPriceOracle__factory";
export { MockPriceOracle__factory } from "./MockPriceOracle__factory";
