/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IUniswapOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getABDSPriceInETH"
      | "getABDSPriceInUSDC"
      | "getABDSPriceInUSDT"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getABDSPriceInETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getABDSPriceInUSDC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getABDSPriceInUSDT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getABDSPriceInETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getABDSPriceInUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getABDSPriceInUSDT",
    data: BytesLike
  ): Result;
}

export interface IUniswapOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IUniswapOracle;
  waitForDeployment(): Promise<this>;

  interface: IUniswapOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getABDSPriceInETH: TypedContractMethod<[], [bigint], "view">;

  getABDSPriceInUSDC: TypedContractMethod<[], [bigint], "view">;

  getABDSPriceInUSDT: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getABDSPriceInETH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getABDSPriceInUSDC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getABDSPriceInUSDT"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
