/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface UniswapV2PriceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "abdsEthPool"
      | "abdsUsdcPool"
      | "abdsUsdtPool"
      | "getABDSPriceInETH"
      | "getABDSPriceInUSDC"
      | "getABDSPriceInUSDT"
      | "owner"
      | "renounceOwnership"
      | "setPools"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

  encodeFunctionData(
    functionFragment: "abdsEthPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "abdsUsdcPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "abdsUsdtPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getABDSPriceInETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getABDSPriceInUSDC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getABDSPriceInUSDT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPools",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "abdsEthPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "abdsUsdcPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "abdsUsdtPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getABDSPriceInETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getABDSPriceInUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getABDSPriceInUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UniswapV2PriceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): UniswapV2PriceOracle;
  waitForDeployment(): Promise<this>;

  interface: UniswapV2PriceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  abdsEthPool: TypedContractMethod<[], [string], "view">;

  abdsUsdcPool: TypedContractMethod<[], [string], "view">;

  abdsUsdtPool: TypedContractMethod<[], [string], "view">;

  getABDSPriceInETH: TypedContractMethod<[], [bigint], "view">;

  getABDSPriceInUSDC: TypedContractMethod<[], [bigint], "view">;

  getABDSPriceInUSDT: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPools: TypedContractMethod<
    [
      _abdsUsdtPool: AddressLike,
      _abdsUsdcPool: AddressLike,
      _abdsEthPool: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "abdsEthPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "abdsUsdcPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "abdsUsdtPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getABDSPriceInETH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getABDSPriceInUSDC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getABDSPriceInUSDT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPools"
  ): TypedContractMethod<
    [
      _abdsUsdtPool: AddressLike,
      _abdsUsdcPool: AddressLike,
      _abdsEthPool: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
