/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPriceOracle__factory } from "./IPriceOracle__factory";
export { PriceOracle__factory } from "./PriceOracle__factory";
