/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockPriceOracleSol from "./MockPriceOracle.sol";
export * as uniswapV2PriceOracleSol from "./UniswapV2PriceOracle.sol";
export * as stakingSol from "./staking.sol";
export * as tokenSol from "./token.sol";
export { SimpleToken__factory } from "./SimpleToken__factory";
