/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IUniswapOracle } from "./IUniswapOracle";
export type { UniswapV2PriceOracle } from "./UniswapV2PriceOracle";
