/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IUniswapOracle__factory } from "./IUniswapOracle__factory";
export { UniswapV2PriceOracle__factory } from "./UniswapV2PriceOracle__factory";
